version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: toren
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

  app:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=mysql+pymysql://root:root@db:3306/toren
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - app_network
    command: >
      sh -c "./wait-for-it.sh db 3306 -- flask run --host=0.0.0.0 --port=5000"

networks:
  app_network:
    driver: bridge

volumes:
  db_data:
