version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db
    command: >
      sh -c "./wait-for-it.sh db:3306 -- python app.py"
    environment:
      - DATABASE_URL=mysql+pymysql://root:root@db:3306/toren

  db:
    image: mysql:latest
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: toren
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
